# Generated by Django 3.2.4 on 2021-08-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIEACTapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InattentivedBigram',
            new_name='InattentiveBigram',
        ),
    ]
