# Generated by Django 3.2.4 on 2021-08-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIEACTapp', '0004_auto_20210802_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='OFFRNARR',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
