# Generated by Django 3.2.4 on 2021-09-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIEACTapp', '0008_auto_20210803_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='POSBIGRAM',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='POSTRIGRAM',
            field=models.CharField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='POSUNIGRAM',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
