# Generated by Django 3.2.4 on 2021-08-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIEACTapp', '0003_auto_20210802_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatabase',
            name='CRSCATGRY',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='CRSCATGRYINT',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='CRSHTYPE',
        ),
    ]
