# Generated by Django 3.2.4 on 2021-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIEACTapp', '0005_alter_userdatabase_offrnarr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='POSUNIGRAM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
